---
name: Test

on:
    pull_request:
    push:
        branches:
            - master
            - main

jobs:
    pytest:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ["3.12"]
                os: [ubuntu-latest, macOS-latest, windows-latest]

        steps:
            - name: "Checkout the repository"
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true

            - name: Install Python
              run: uv python install ${{ matrix.python-version }}

            - name: Install dependencies
              run: uv sync --all-extras --dev

            - name: Run Tests
              run: uv run pytest --verbose
